###    DROPDOWN FOR FORMS

GET http://localhost:4321/dropdown/dropdownMajorType

###

GET http://localhost:4321/dropdown/dropdownSubTypeWithMajor/2001

###

GET http://localhost:4321/dropdown/dropdownDept

###

GET http://localhost:4321/dropdown/dropdownFacultyWithDept/1

###

GET http://localhost:4321/dropdown/dropdownVenue

### LOGIN

POST http://localhost:4321/filter/loginCredentials
Content-Type: application/json

{
    "faculty_id":6000,
    "faculty_password":"sridhar@cse"
}

###

GET http://localhost:4321/dropdown/currentAcademicYear

###

GET http://localhost:4321/filter/getCurrPrevAcdYrWithSubType/3001