
###

GET http://localhost:1234/seminar/dept/1

### HoD is receiving the requested proposal
GET http://localhost:1234/seminar/loadforlevel1/data_management_seminar/1/6001

###

### HoD approves the proposal
PUT http://localhost:1234/seminar/acknowledgelevel1/1/6001/1

###

### Principal is receiving the requested proposal
GET http://localhost:1234/seminar/loadforlevel2

###

### Principal approves the proposal
PUT http://localhost:1234/seminar/acknowedgelevel2/1/2

###

################## Proposal over #####################

###

### Faculty is receiving his/her proposal after approved
GET http://localhost:1234/ecrWorkshop/loadforCompletion/1

###

### Faculty is updating the completion report
PUT http://localhost:1234/ecrWorkshop/ecrCompletion/RPT0000001
Content-Type: application/json

{
    "event_photo_1":"photo/path1",
    "event_photo_2":"photo/path2",
    "event_po":"1,2,3,4",
    "completion_date":"0000-00-00",
    "completion_hod":"0000-00-00",
    "completion_principal":"0000-00-00",
    "pdf":"pdf/path",
    "event_duration":"3hrs",
    "event_os":"Dr. G. Kavitha",
    "event_time":"10 am",
    "event_description":"The event was about how to develop a webpage using React JS",
    "event_budget_utilized":50000
}

###

### HoD is receiving the completion report
GET http://localhost:1234/ecrWorkshop/eventcompletionloadlevel1/1/6001

###

### HoD approves the completion report
PUT http://localhost:1234/ecrWorkshop/completionacknowledgelevel1/1/6001

###

### Principal is receiving the completion report
GET http://localhost:1234/ecrWorkshop/completionloadlevel2/1

###

### Principal approves the completion report
PUT http://localhost:1234/ecrWorkshop/completionacknowledgelevel2/1/RPT0000001

###

GET http://localhost:1234/seminar/find

###